import { validateCommand } from '../../shared/sim/frontier/engine';
import { EXPEDITION_ACTIONS } from '../../shared/sim';
import { ApiError } from './portable';
import {
  CHAT_NEARBY_RADIUS, INVITE_PARAM, MAX_OFFER_LEN, MAX_TRADE_STACKS, TRADE_BREAK_RANGE, TRADE_RANGE,
  DUMMY_ID, DUMMY_MAX_HP, DUMMY_TILE, GIANT_ID, GIANT_REACH, GIANT_TILE, RAID_INTERVAL_MS, RAID_MIN_CONTRIBUTION, RAID_REWARD, RAID_WINDOW_MS, raidMaxHp, EMOTE_LIST, GRID_SIZE, HOTBAR_SIZE, INVENTORY_SIZE, MAX_CHAT_LEN, PUNCH_DAMAGE, RECIPES, STICK_DROP_CHANCE, STICK_ITEM_ID, STONE_CLUB_ITEM_ID, getItemDef, validAppearance, COSMETICS,
} from '../../shared/sim';
import { GARDEN_BASE_PLOTS, GARDEN_CROPS, GARDEN_EXTRA_PLOT_LEVEL, GARDEN_MAX_PLOTS, GARDEN_REACH } from '../../shared/sim';

type Field = { type: 'integer'; minimum: number; maximum: number } | { type: 'string'; minLength: number; maxLength: number; pattern?: string; enum?: string[] };
type Action = { description: string; properties: Record<string, Field>; required: string[]; scope?: 'combat' | 'chat' };
const integer = (minimum: number, maximum: number): Field => ({ type: 'integer', minimum, maximum });
const text = (minLength: number, maxLength: number, pattern?: string): Field => ({ type: 'string', minLength, maxLength, ...(pattern ? { pattern } : {}) });
const playerId = text(64, 64, '^[0-9a-fA-F]{64}$');
const slot = integer(0, INVENTORY_SIZE - 1);
const hotbarSlot = integer(0, HOTBAR_SIZE - 1);
const stickDamage = getItemDef(STICK_ITEM_ID)!.weaponDamage;
const clubDamage = getItemDef(STONE_CLUB_ITEM_ID)!.weaponDamage;
const nodeId = integer(1, 4294967295);
const stickChance = `${Math.round(STICK_DROP_CHANCE * 100)}%`;
const tradeId = text(1, 20, '^[0-9]+$');
export const ACTIONS: Record<string, Action> = {
  frontier: { description: 'Settlements, quests, construction, creatures and sailing. Send a JSON command string with action and documented arguments; inspect state.frontier for IDs, costs, deadlines, recipes and permissions. The home island is continuous: walk accepts id bramblewild or settlement and local x,z; enter/return queue walking along the harbour trail. Actions: enter, return, walk, move, stop, talk, quest, order, gather, craft, claim, tax, upgrade, permit, abandon, challenge, join_contest, attack, build, move_building, dismantle, container, specialize, observe, tame, train, companion, ability, plant, harvest_crop, boat, boat_permit, board, pilot, sail, dock, disembark, eat, equip, pickup_bag, invite_contest, survey, brace, restore_shrine. Personal banking uses container with id vault-<own identity>, target deposit or withdraw, item and quantity at Meadows town. specialize accepts earlySwitch:true to pay the displayed early-switch total. restore_shrine uses a shrine id from state.frontier.shrines; stand beside it with its materials.', properties: { command: text(2, 2048) }, required: ['command'] },
  expedition: { description: 'On-demand giant berry expedition, alone with NPC help or with other players. See state.adventure for positions, members and messages. Start at camp; join uses expeditionId. Other actions require membership and expeditionId. Pass needs playerId; roll needs x,z. Bait/bribe spend a greenberry unless a technique changes the cost. Deliver at market (35,37), feed at (12,36). Cooldowns and proximity are enforced.', properties: { action: { type: 'string', minLength: 4, maxLength: 16, enum: [...EXPEDITION_ACTIONS] }, expeditionId: text(1, 20, '^[0-9]+$'), playerId, x: integer(9, 41), z: integer(9, 41), destination: { type: 'string', minLength: 5, maxLength: 6, enum: ['market', 'feast'] } }, required: ['action'] },
  technique: { description: 'Toggle one unlocked technique in your three-slot loadout. Stand within four tiles of camp (22,18). See state.progression.techniques for the IDs, effects, and unlock requirements.', properties: { technique: integer(0,14) }, required: ['technique'] },
  project: { description: 'Donate one driftwood or obsidian at camp to the persistent shared workshop. At 20 driftwood and 10 obsidian all future expedition berries gain a reward. Contributions award Building XP.', properties: { itemId: { type: 'string', minLength: 8, maxLength: 9, enum: ['driftwood', 'obsidian'] } }, required: ['itemId'] },
  garden_share: { description: 'Publish or remove a read-only view of your garden for others. 1 shares, 0 hides. Only you can plant or harvest.', properties: { shared: integer(0,1) }, required: ['shared'] },
  duel: { description: 'Friendly sparring: challenge a nearby player outside the safe ring, then they accept. Three-second countdown, separate 30 practice HP, alternating swings at melee range. Surrender at any time. No ordinary HP or items lost; newcomer protection does not block mutual consent.', properties: { action: { type: 'string', minLength: 6, maxLength: 9, enum: ['challenge', 'accept', 'decline', 'surrender'] }, playerId }, required: ['action','playerId'], scope: 'combat' },
  move: { description: 'Walk to a tile. The server paths around trees. A rounded thorny boundary surrounds the Grove (state.world.brambles.tiles): without a sturdy stick you stop at the last Grove tile and the receipt has blockedBy "brambles" and the clamped destination. From the Coast you can always walk home. The Boulders (state.world.boulders) lie past a boulder line on the old south-east shoreline: crossing it needs a stone club (blockedBy "boulders" otherwise); water is impassable (blockedBy "sea"); state.world.map gives the coastline, river crossings, obstacles and named destinations.', properties: { x: integer(0, GRID_SIZE - 1), z: integer(0, GRID_SIZE - 1) }, required: ['x', 'z'] },
  harvest: { description: `Walk to and harvest a node from state.nodes: a berry tree, a driftwood pile or a tide rock (the last two are on the Coast, past the brambles). Pass nodeId (treeId is the old alias), or kind (berry, driftwood or tide_rock) for the node of that kind with the soonest claim; with neither, the berry tree with the soonest claim (as state.goal suggests). A regrowing or busy node is not an error: you wait beside it and claim it when it ripens (newcomers first, then whoever waited longest); the receipt then has waiting {treeId, ripeInTicks}. A berry harvest gives one berry and, Foraging XP. At level 2 (four berry harvests), you receive a guaranteed first stick; after that there is a ${stickChance} chance to find spare sticks: a weapon and the key through the brambles. Driftwood piles give driftwood, tide rocks flint, obsidian outcrops (in the Boulders, past the boulder line: needs a stone club) obsidian; they never find sticks. Inspect state to confirm completion.`, properties: { nodeId, treeId: nodeId, kind: { type: 'string', minLength: 1, maxLength: 16, enum: ['berry', 'driftwood', 'tide_rock', 'obsidian'] } }, required: [] },
  craft: { description: `Make an item from a recipe in state.recipes, instantly (the verb "make"). ${RECIPES.map(r => `${r.id} = ${r.inputs.map(i => `${i.quantity} ${i.itemId}`).join(' + ')}${r.level > 1 ? ` (Crafting level ${r.level})` : ''}`).join('; ')}. stone_club is a one-handed weapon dealing ${clubDamage} damage and the flint_knife ${getItemDef('flint_knife')!.weaponDamage}, both wielded like the stick; berry_mash is food (+${getItemDef('berry_mash')!.healthRestore} HP); driftwood_crown makes no item but unlocks a keepsake to wear. A recipe above your Crafting level is locked (state.recipes[].locked; error "Needs Crafting level N"). Every make earns Crafting XP. Rejected while dead or attacking; if the bag is full the result lands on the ground under you.`, properties: { recipe: { type: 'string', minLength: 1, maxLength: 32, enum: RECIPES.map(r => r.id) } }, required: ['recipe'] },
  wear: { description: 'Wear an earned keepsake (state.cosmetics.all[].unlocked) in its slot, or pass cosmetic "none" to take that slot off. Purely visual; everyone sees it.', properties: { slot: { type: 'string', minLength: 4, maxLength: 4, enum: ['head', 'neck'] }, cosmetic: { type: 'string', minLength: 4, maxLength: 24, enum: ['none', ...COSMETICS.map(c => c.key)] } }, required: ['slot', 'cosmetic'] },
  eat: { description: 'Eat one berry in your inventory slot.', properties: { slot }, required: ['slot'] },
  wield: { description: `Wield the weapon in quick slot 0-${HOTBAR_SIZE - 1} (inventory slots 0-${HOTBAR_SIZE - 1}). A stick deals ${stickDamage} damage per swing instead of the ${PUNCH_DAMAGE}-damage punch and is visible in your hand. Moving, dropping, or trading away its last quick-slot copy unwields it, as does dying.`, properties: { slot: hotbarSlot }, required: ['slot'] },
  unwield: { description: `Put your weapon away and punch for ${PUNCH_DAMAGE} damage.`, properties: {}, required: [] },
  stop: { description: 'Stop movement, harvesting, following, and combat.', properties: {}, required: [] },
  attack: { description: `Start combat with an online player who also has combat access. You swing every few ticks: a punch deals ${PUNCH_DAMAGE} damage, a wielded stick ${stickDamage}, a stone club ${clubDamage}. Rejected while either of you is in the safe ring around spawn (state.world.safeRing) or the target is in grace (10 ticks after a respawn; a newcomer until they find a stick, attack, or 3 minutes pass). Attacking ends your own grace.`, properties: { playerId }, required: ['playerId'], scope: 'combat' },
  attack_dummy: { description: `Walk up to the training dummy in the Grove (state.dummies; tile ${DUMMY_TILE.x},${DUMMY_TILE.z}, just outside the safe ring) and keep swinging at it with your punch or wielded weapon. Open to everyone (no combat access needed), allowed in the safe ring and during grace, which it does not end. It harms nobody and never dies: ${DUMMY_MAX_HP} HP that springs back to full. Moving, harvesting, attacking a player or being hit stops it.`, properties: { dummyId: integer(DUMMY_ID, DUMMY_ID) }, required: [] },
  attack_giant: { description: `Walk up to the Giant in the Boulders (state.giant; centre tile ${GIANT_TILE.x},${GIANT_TILE.z}, blocking the 3x3 around it) and keep swinging at it from any tile within Chebyshev ${GIANT_REACH} of its centre. A PvE world boss open to everyone (no combat access needed): it never ends grace or makes you hostile. Reaching the Boulders needs a stone club (bag or wielded); without one the call fails with error code boulders (or brambles in the Grove without a stick). It sleeps between scheduled raids (every ${RAID_INTERVAL_MS / 60_000} minutes at :00, :20 and :40 UTC; state.giant.nextWakeAt) and cannot be attacked asleep (error). A raid lasts ${RAID_WINDOW_MS / 60000} minutes with ${raidMaxHp(1)}-${raidMaxHp(Number.MAX_SAFE_INTEGER)} HP shared by everyone (scaled by the players in the Boulders at the wake). It telegraphs slow blows at tiles (state.giant.telegraph): walk out of the marked square before landsInTicks reaches 0, then attack_giant again. Everyone who dealt at least ${RAID_MIN_CONTRIBUTION} damage when it falls gets ${RAID_REWARD.quantity} obsidian and the Giant's Tooth keepsake (cosmetic). Moving, harvesting, attacking a player or being hit stops the swings.`, properties: { giantId: integer(GIANT_ID, GIANT_ID) }, required: [] },
  emote: { description: `A cosmetic emote everyone nearby sees: ${EMOTE_LIST.map(e => e.key).join(', ')}. Moving or acting ends it (sit holds until then). At most one every 2 ticks.`, properties: { emote: { type: 'string', minLength: 2, maxLength: 8, enum: EMOTE_LIST.map(e => e.key) } }, required: ['emote'] },
  follow: { description: 'Follow an online player.', properties: { playerId }, required: ['playerId'] },
  pickup: { description: 'Walk to and pick up a ground item. Use its string ID from state. An item beyond the brambles is rejected (error code brambles) unless you hold a stick.', properties: { id: text(1, 20, '^[0-9]+$') }, required: ['id'] },
  drop: { description: 'Drop items from your own inventory.', properties: { slot, quantity: integer(1, 99) }, required: ['slot', 'quantity'] },
  inventory_move: { description: 'Move or swap your inventory slots.', properties: { from: slot, to: slot }, required: ['from', 'to'] },
  name: { description: 'Set your character name.', properties: { name: text(2, 16, '^[A-Za-z0-9_ ]+$') }, required: ['name'] },
  appearance: { description: 'Choose the character cosmetics listed in state.', properties: { hairStyle: integer(0, 8), skinTone: integer(0, 255), hairColor: integer(0, 255), robeColor: integer(0, 255), wrapColor: integer(0, 255) }, required: ['hairStyle', 'skinTone', 'hairColor', 'robeColor', 'wrapColor'] },
  chat: { description: `Send a public game message. Requires chat access. Wait at least three seconds between messages. Each message in state.chat has nearby: true when it was said within ${CHAT_NEARBY_RADIUS} tiles of you.`, properties: { text: text(1, MAX_CHAT_LEN) }, required: ['text'], scope: 'chat' },
  invite_create: { description: `Make (or replace) your one-hour "join me" code. Anyone who redeems it becomes your friend and is placed beside you (or at the nearest Grove tile if you are past the brambles and they hold no stick). Share only the code or the link query ?${INVITE_PARAM}=CODE; it never contains credentials. Receipt: {code, linkQuery}; also in state.invite.`, properties: {}, required: [] },
  invite_redeem: { description: "Redeem another player's invite code: you both become friends and, unless you are fighting or down, you are placed beside them. Receipt: your new tile and area; the explanation arrives in state.notices.", properties: { code: text(8, 12, '^[A-Za-z0-9 -]+$') }, required: ['code'] },
  friend_add: { description: "Add a player to your friends list (one-way). state.friends shows each friend's online status, area and tile; use follow to walk to them.", properties: { playerId }, required: ['playerId'] },
  friend_remove: { description: 'Remove a player from your friends list.', properties: { playerId }, required: ['playerId'] },
  trade_request: { description: `Walk toward a player and request a trade within ${TRADE_RANGE} tiles (if they already asked you, this accepts). state.player.action shows walking to trade; stop cancels the approach. One trade at a time. See state.trade.`, properties: { playerId }, required: ['playerId'] },
  trade_respond: { description: 'Accept or decline a trade request you received (state.trade.status requested_by_them).', properties: { tradeId, answer: { type: 'string', minLength: 6, maxLength: 7, enum: ['accept', 'decline'] } }, required: ['tradeId', 'answer'] },
  trade_coins: { description: 'Set the coin portion of your accepted trade. Changing coins clears both confirmations. See state.trade for both coin offers.', properties: { tradeId, coins: integer(0, 1000000) }, required: ['tradeId','coins'] },
  trade_offer: { description: `Set everything you offer in the open trade, as itemId:quantity pairs joined by commas (e.g. berry_blueberry:2,stick:1; "" for nothing; at most ${MAX_TRADE_STACKS} kinds). Items stay in your inventory until the swap; wielded weapons can be offered too. Any change clears both confirmations.`, properties: { tradeId, offer: { type: 'string', minLength: 0, maxLength: MAX_OFFER_LEN } }, required: ['tradeId', 'offer'] },
  trade_confirm: { description: `Confirm the open trade exactly as it stands in state.trade. When both sides have confirmed, the swap happens at once, all or nothing; if a bag is too full or an offered item is gone, nothing moves, both confirmations clear and state.notices says why. After a successful swap, weapons without a remaining quick-slot copy are put away; received weapons go to the bag without being equipped. Walking beyond ${TRADE_BREAK_RANGE} tiles, dying or leaving cancels.`, properties: { tradeId }, required: ['tradeId'] },
  trade_cancel: { description: 'Cancel your trade or withdraw your request.', properties: { tradeId }, required: ['tradeId'] },
  plant: { description: `Plant one berry from your bag in a plot of your personal garden (state.garden; the terrace tiles are in state.garden.plots[].tile, just north-west of the safe ring). It grows in real time, even while you are offline: ${GARDEN_CROPS.map(c => `${c.itemId} ${c.growMs / 3600000}h -> ${c.yield}`).join(', ')}. You must stand within Chebyshev ${GARDEN_REACH} of the plot; from farther away this walks you there and returns walking (send plant again on arrival). ${GARDEN_BASE_PLOTS} plots, a ${GARDEN_MAX_PLOTS}th at Foraging level ${GARDEN_EXTRA_PLOT_LEVEL}. Plants are private until you opt into garden_share; visitors cannot change them.`, properties: { plot: integer(0, GARDEN_MAX_PLOTS - 1), berry: { type: 'string', minLength: 1, maxLength: 32, enum: GARDEN_CROPS.map(c => c.itemId) } }, required: ['plot', 'berry'] },
  harvest_garden: { description: `Harvest a ripe plot of your garden (state.garden.plots[].ripe): it gives the berries and Foraging XP. Ripe plants never wither, so there is no hurry. Rejected when unripe, or when your bag cannot take the berries (the plant stays). Same reach rule as plant (walks you there first).`, properties: { plot: integer(0, GARDEN_MAX_PLOTS - 1) }, required: ['plot'] },
};

export function validateObject(input: unknown, properties: Record<string, Field>, required: string[]): Record<string, any> {
  const bad = () => new ApiError(400, 'invalid_arguments', 'Use the exact fields and types documented in openapi.json.');
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw bad();
  const value = input as Record<string, any>;
  if (Object.keys(value).some(key => !Object.hasOwn(properties, key)) || required.some(key => !Object.hasOwn(value, key))) throw bad();
  for (const [key, entry] of Object.entries(value)) {
    const field = properties[key];
    if (field.type === 'integer') {
      if (!Number.isInteger(entry) || entry < field.minimum || entry > field.maximum) throw bad();
    } else if (typeof entry !== 'string' || entry.length < field.minLength || entry.length > field.maxLength
      || (field.pattern && !new RegExp(field.pattern).test(entry)) || (field.enum && !field.enum.includes(entry))) throw bad();
  }
  return value;
}

export function validateAction(name: string, input: unknown) {
  if (!Object.hasOwn(ACTIONS, name)) throw new ApiError(404, 'unknown_action', 'Unknown action. See openapi.json.');
  const action = ACTIONS[name];
  const value = validateObject(input, action.properties, action.required);
  if (name === 'frontier') {
    try { validateCommand(JSON.parse(value.command)); }
    catch (error) { throw new ApiError(400, 'invalid_arguments', (error as Error).message); }
  }
  if (name === 'expedition' && ((value.action === 'roll' && (value.x === undefined || value.z === undefined)) || (value.action === 'pass' && !value.playerId) || (value.action !== 'start' && !value.expeditionId))) throw new ApiError(400, 'invalid_arguments', 'This action needs expeditionId; roll also needs x and z, pass needs playerId.');
  if (name === 'appearance' && !validAppearance(value as any)) throw new ApiError(400, 'invalid_appearance', 'Choose styles from the appearance options in state.');
  if (name === 'pickup' && BigInt(value.id) > 18446744073709551615n) throw new ApiError(400, 'invalid_id', 'Ground item ID is too large.');
  if (typeof value.expeditionId === 'string' && BigInt(value.expeditionId) > 18446744073709551615n) throw new ApiError(400, 'invalid_id', 'Expedition ID is too large.');
  if (typeof value.tradeId === 'string' && BigInt(value.tradeId) > 18446744073709551615n) throw new ApiError(400, 'invalid_id', 'Trade ID is too large.');
  return value;
}

const json = (schema: object) => ({ 'application/json': { schema } });
const object = (properties: object, required: string[]) => ({ type: 'object', properties, required, additionalProperties: false });
const error = { description: 'Request rejected. Errors contain error.code and error.message. On 429 honor Retry-After.' };
const actionResponse = { description: 'Action accepted; inspect state to confirm its eventual result. Repeating an identical Idempotency-Key returns the saved receipt.' };
const permissions = object({ combat: { type: 'boolean' }, chat: { type: 'boolean' } }, ['combat', 'chat']);
const sessionResponse = { description: 'Bearer token shown once. Never place it in a URL.', content: json(object({
  token: { type: 'string', description: 'Secret bearer token for subsequent requests.' },
  renewToken: { type: 'string', description: 'Secret return token, valid 30 days and rotated on every return. Store securely.' },
  sessionId: { type: 'string', format: 'uuid' }, playerId, expiresAt: { type: 'string', format: 'date-time' },
  permissions, pollIntervalMs: { type: 'integer', const: 1000 },
}, ['token', 'sessionId', 'playerId', 'expiresAt', 'permissions', 'pollIntervalMs'])) };
export const openapi = {
  openapi: '3.1.0', info: { title: 'BeriGame Agent API', version: '1.6.0' }, servers: [{ url: '/api/agent/v1' }],
  components: { securitySchemes: { session: { type: 'http', scheme: 'bearer', description: 'Session token from POST /sessions. Invitations are accepted only at POST /sessions.' }, invite: { type: 'http', scheme: 'bearer', description: 'Single-use invite code provided by the world operator.' } } },
  paths: {
    '/sessions': { post: { operationId: 'join_game', summary: 'Redeem an invite for a player session', security: [{ invite: [] }], requestBody: { required: true, content: json(object({}, [])) }, responses: { '201': sessionResponse, '401': error, '429': error, '503': error } } },
    '/renewals': { post: { operationId: 'return_to_character', 'x-hosted-only': true, summary: 'Hosted beta: return with your saved renewToken as the bearer token. Receives a new session token and rotated renewToken; save both. Keeps inventory, skills and garden.', security: [{ session: [] }], requestBody: { required: true, content: json(object({}, [])) }, responses: { '200': sessionResponse, '401': error, '429': error } } },
    '/recovery': { post: { operationId: 'export_character_recovery', 'x-hosted-only': true, summary: 'Export a replacement recovery key with a valid session or renewal bearer. Store it privately. Optional character-access recovery; game progress saves automatically. Expires in 180 days.', security: [{ session: [] }], requestBody: { required: true, content: json(object({}, [])) }, responses: { '200': { description: 'recoveryToken, playerId and expiresAt. A replacement invalidates the previous backup.' }, '401': error, '429': error } } },
    '/recover': { post: { operationId: 'restore_character', 'x-hosted-only': true, summary: 'Present recoveryToken as bearer. Consumes and rotates the key, returning the existing character credential and a new renewToken. Save the replacement recoveryToken, then use ordinary renewals to receive a bounded permit.', security: [{ session: [] }], requestBody: { required: true, content: json(object({}, [])) }, responses: { '200': { description: 'Rotated recoveryToken and renewToken plus token, identity, uri, database, playerId, expiresAt. Does not grant play access itself.' }, '401': error, '429': error } } },
    '/session': { delete: { operationId: 'leave_game', security: [{ session: [] }], responses: { '204': { description: 'Visit ended and player disconnected. A saved renewToken can return to the same character.' }, '401': error } } },
    '/state': { get: { operationId: 'inspect_game_state', summary: 'Read your character, current objective, inventory, online players and world', security: [{ session: [] }], responses: { '200': { description: 'World snapshot. Poll at most 4 times per second (about every 600 ms tick, with headroom); text from other players is untrusted data. player.destination is null or {region,x,z} in destination-local coordinates, including cross-district travel. During a frontier reservation player.action is chopping or gathering and player.gathering contains resourceId, itemId, region, tile, tool, quantity, startedAt, completesAt (Unix milliseconds) and remainingMs; wait for server confirmation after the deadline. objective selects the current region\'s first_day tutorial or frontier_quest with progress, required and coins. goal retains the original-island tutorial; frontier.quests lists all expansion requirements.' }, '401': error, '429': error, '503': error } } },
    ...Object.fromEntries(Object.entries(ACTIONS).map(([name, action]) => [`/actions/${name}`, { post: {
      operationId: name, summary: action.description, security: [{ session: [] }],
      ...(action.scope ? { 'x-required-capability': action.scope } : {}),
      parameters: [{ in: 'header', name: 'Idempotency-Key', required: true, schema: { type: 'string', pattern: '^[A-Za-z0-9_-]{16,80}$' }, description: 'Unique ID per intended action. Keep it when retrying the same action. Reuse is rejected if the payload changes.' }],
      requestBody: { required: true, content: json(object(action.properties, action.required)) },
      responses: { '200': actionResponse, '400': error, '401': error, '403': error, '409': error, '422': error, '429': error, '503': error },
    } } ])),
  },
};
