// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  growingXp: __t.u32().name("growing_xp"),
  buildingXp: __t.u32().name("building_xp"),
  exploringXp: __t.u32().name("exploring_xp"),
  fightingXp: __t.u32().name("fighting_xp"),
  befriendingXp: __t.u32().name("befriending_xp"),
  feats: __t.u32(),
  loadout: __t.u32(),
  completions: __t.u32(),
  giantTrust: __t.u32().name("giant_trust"),
  stickClaimed: __t.bool().name("stick_claimed"),
});
