// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  hairStyle: __t.u8().name("hair_style"),
  skinTone: __t.u8().name("skin_tone"),
  hairColor: __t.u8().name("hair_color"),
  robeColor: __t.u8().name("robe_color"),
  wrapColor: __t.u8().name("wrap_color"),
  bodyType: __t.u8().name("body_type"),
  faceShape: __t.u8().name("face_shape"),
  eyeColor: __t.u8().name("eye_color"),
  facialHair: __t.u8().name("facial_hair"),
  outfitStyle: __t.u8().name("outfit_style"),
  trouserColor: __t.u8().name("trouser_color"),
  bootColor: __t.u8().name("boot_color"),
  accessory: __t.u8(),
  accessoryColor: __t.u8().name("accessory_color"),
  setupComplete: __t.bool().name("setup_complete"),
});
