// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u8().primaryKey(),
  clatterhornOpen: __t.bool().name("clatterhorn_open"),
  spireOpen: __t.bool().name("spire_open"),
  spirePracticeOpen: __t.bool().name("spire_practice_open"),
  spireMaxRuns: __t.u8().name("spire_max_runs"),
  spireHpBase: __t.u32().name("spire_hp_base"),
  spireHpPerMember: __t.u32().name("spire_hp_per_member"),
  clatterHpBase: __t.u32().name("clatter_hp_base"),
  clatterHpPerChallenger: __t.u32().name("clatter_hp_per_challenger"),
});
