// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tick: __t.u32(),
  boss: __t.u8(),
  kind: __t.u8(),
  runId: __t.u64().name("run_id"),
  player: __t.identity(),
  x: __t.i32(),
  z: __t.i32(),
  quantity: __t.u32(),
  value: __t.u32(),
  text: __t.string(),
});
