// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  x: __t.i32(),
  z: __t.i32(),
  hp: __t.u32(),
  maxHp: __t.u32().name("max_hp"),
  state: __t.u8(),
  phase: __t.u8(),
  stateUntilTick: __t.u32().name("state_until_tick"),
  attack: __t.u8(),
  dir: __t.u8(),
  endX: __t.i32().name("end_x"),
  endZ: __t.i32().name("end_z"),
  endKind: __t.u8().name("end_kind"),
  chain: __t.u8(),
  attackCount: __t.u32().name("attack_count"),
  bait: __t.u32(),
  swarmTick: __t.u32().name("swarm_tick"),
  swarmSide: __t.u8().name("swarm_side"),
  swarmFree: __t.u8().name("swarm_free"),
  engagedTick: __t.u32().name("engaged_tick"),
  lastHitTick: __t.u32().name("last_hit_tick"),
  challengers: __t.u32(),
  fightCount: __t.u32().name("fight_count"),
  defeats: __t.u32(),
  owedLeft: __t.u32().name("owed_left"),
});
