// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tick: __t.u32(),
  kind: __t.u8(),
  attacker: __t.identity(),
  defender: __t.identity(),
  damage: __t.u8(),
  attackerStance: __t.u8().name("attacker_stance"),
  defenderStance: __t.u8().name("defender_stance"),
  attackerState: __t.u8().name("attacker_state"),
  defenderState: __t.u8().name("defender_state"),
  defenderHp: __t.u8().name("defender_hp"),
});
