// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  clatterhornOpen: __t.bool(),
  spireOpen: __t.bool(),
  spirePracticeOpen: __t.bool(),
  spireMaxRuns: __t.u8(),
  spireHpBase: __t.u32(),
  spireHpPerMember: __t.u32(),
  clatterHpBase: __t.u32(),
  clatterHpPerChallenger: __t.u32(),
};
