// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  leader: __t.identity(),
  stage: __t.string(),
  startedTick: __t.u32().name("started_tick"),
  untilTick: __t.u32().name("until_tick"),
  ripeTick: __t.u32().name("ripe_tick"),
  x: __t.i32(),
  z: __t.i32(),
  carrier: __t.option(__t.identity()),
  mossCarrying: __t.bool().name("moss_carrying"),
  mossPaid: __t.bool().name("moss_paid"),
  porter: __t.option(__t.identity()),
  lastActiveTick: __t.u32().name("last_active_tick"),
  value: __t.u8(),
  split: __t.bool(),
  mossX: __t.i32().name("moss_x"),
  mossZ: __t.i32().name("moss_z"),
  pipX: __t.i32().name("pip_x"),
  pipZ: __t.i32().name("pip_z"),
  giantX: __t.i32().name("giant_x"),
  giantZ: __t.i32().name("giant_z"),
  hiddenUntil: __t.u32().name("hidden_until"),
  pipUntil: __t.u32().name("pip_until"),
  giantUntil: __t.u32().name("giant_until"),
  baitX: __t.i32().name("bait_x"),
  baitZ: __t.i32().name("bait_z"),
  baitUntil: __t.u32().name("bait_until"),
  guardUntil: __t.u32().name("guard_until"),
  message: __t.string(),
  destination: __t.string(),
});
