// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  a: __t.identity(),
  b: __t.identity(),
  stage: __t.string(),
  startsTick: __t.u32().name("starts_tick"),
  expiresTick: __t.u32().name("expires_tick"),
  aHp: __t.u8().name("a_hp"),
  bHp: __t.u8().name("b_hp"),
  nextSwingTick: __t.u32().name("next_swing_tick"),
  turnA: __t.bool().name("turn_a"),
  result: __t.string(),
});
