// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  x: __t.i32(),
  z: __t.i32(),
  hp: __t.u32(),
  maxHp: __t.u32().name("max_hp"),
  state: __t.u8(),
  attack: __t.u8(),
  stateUntilTick: __t.u32().name("state_until_tick"),
  slamX: __t.i32().name("slam_x"),
  slamZ: __t.i32().name("slam_z"),
  attackCount: __t.u32().name("attack_count"),
  respawnTick: __t.u32().name("respawn_tick"),
  lastHitTick: __t.u32().name("last_hit_tick"),
});
