// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  awake: __t.bool(),
  nextWakeAtMicros: __t.u64().name("next_wake_at_micros"),
  raidEndsAtMicros: __t.u64().name("raid_ends_at_micros"),
  announced: __t.u8(),
  raidPlayers: __t.u32().name("raid_players"),
  lastOutcome: __t.u8().name("last_outcome"),
  raidCount: __t.u32().name("raid_count"),
});
