// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  itemId: __t.string().name("item_id"),
  quantity: __t.u8(),
  x: __t.i32(),
  z: __t.i32(),
  droppedBy: __t.identity().name("dropped_by"),
  droppedTick: __t.u32().name("dropped_tick"),
  expiresTick: __t.u32().name("expires_tick"),
  droppedOnDeath: __t.bool().name("dropped_on_death"),
});
