// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddFriendReducer from "./add_friend_reducer";
import AttackReducer from "./attack_reducer";
import AttackDummyReducer from "./attack_dummy_reducer";
import AttackGiantReducer from "./attack_giant_reducer";
import CancelReducer from "./cancel_reducer";
import CancelTradeRequestReducer from "./cancel_trade_request_reducer";
import ConfigureAccessReducer from "./configure_access_reducer";
import ConfirmTradeReducer from "./confirm_trade_reducer";
import CraftReducer from "./craft_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import DropItemReducer from "./drop_item_reducer";
import EatBerryReducer from "./eat_berry_reducer";
import EmoteReducer from "./emote_reducer";
import FollowReducer from "./follow_reducer";
import GardenDevRipenReducer from "./garden_dev_ripen_reducer";
import GrantAgentReducer from "./grant_agent_reducer";
import GrantPlayerReducer from "./grant_player_reducer";
import HarvestGardenReducer from "./harvest_garden_reducer";
import MoveItemReducer from "./move_item_reducer";
import PickupItemReducer from "./pickup_item_reducer";
import PlantGardenReducer from "./plant_garden_reducer";
import RedeemInviteReducer from "./redeem_invite_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import RenewGrantReducer from "./renew_grant_reducer";
import RequestTradeReducer from "./request_trade_reducer";
import RespondTradeReducer from "./respond_trade_reducer";
import RevokePlayerReducer from "./revoke_player_reducer";
import SendChatReducer from "./send_chat_reducer";
import SetAppearanceReducer from "./set_appearance_reducer";
import SetNameReducer from "./set_name_reducer";
import SetTargetReducer from "./set_target_reducer";
import SetTradeOfferReducer from "./set_trade_offer_reducer";
import StartHarvestReducer from "./start_harvest_reducer";
import UnwieldReducer from "./unwield_reducer";
import WearCosmeticReducer from "./wear_cosmetic_reducer";
import WieldItemReducer from "./wield_item_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccessPolicyRow from "./access_policy_table";
import AppearanceRow from "./appearance_table";
import ChatMessageRow from "./chat_message_table";
import CombatEventRow from "./combat_event_table";
import DummyEventRow from "./dummy_event_table";
import EmoteEventRow from "./emote_event_table";
import FriendRow from "./friend_table";
import GardenPlotRow from "./garden_plot_table";
import GiantRow from "./giant_table";
import GiantEventRow from "./giant_event_table";
import GroundItemRow from "./ground_item_table";
import InventorySlotRow from "./inventory_slot_table";
import InviteCodeRow from "./invite_code_table";
import PlayerRow from "./player_table";
import PlayerCosmeticRow from "./player_cosmetic_table";
import PlayerSkillRow from "./player_skill_table";
import SocialEventRow from "./social_event_table";
import TradeRow from "./trade_table";
import TrainingDummyRow from "./training_dummy_table";
import TreeRow from "./tree_table";
import WorldRow from "./world_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accessPolicy: __table({
    name: 'access_policy',
    indexes: [
      { accessor: 'id', name: 'access_policy_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'access_policy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AccessPolicyRow),
  appearance: __table({
    name: 'appearance',
    indexes: [
      { accessor: 'identity', name: 'appearance_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'appearance_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AppearanceRow),
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'id', name: 'chat_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  combatEvent: __table({
    name: 'combat_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, CombatEventRow),
  dummyEvent: __table({
    name: 'dummy_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, DummyEventRow),
  emoteEvent: __table({
    name: 'emote_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, EmoteEventRow),
  friend: __table({
    name: 'friend',
    indexes: [
      { accessor: 'id', name: 'friend_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'friend_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'friend_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendRow),
  gardenPlot: __table({
    name: 'garden_plot',
    indexes: [
      { accessor: 'id', name: 'garden_plot_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'garden_plot_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'garden_plot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GardenPlotRow),
  giant: __table({
    name: 'giant',
    indexes: [
      { accessor: 'id', name: 'giant_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'giant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GiantRow),
  giantEvent: __table({
    name: 'giant_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, GiantEventRow),
  groundItem: __table({
    name: 'ground_item',
    indexes: [
      { accessor: 'id', name: 'ground_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ground_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GroundItemRow),
  inventorySlot: __table({
    name: 'inventory_slot',
    indexes: [
      { accessor: 'id', name: 'inventory_slot_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'inventory_slot_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'inventory_slot_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InventorySlotRow),
  inviteCode: __table({
    name: 'invite_code',
    indexes: [
      { accessor: 'code', name: 'invite_code_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'inviter', name: 'invite_code_inviter_idx_btree', algorithm: 'btree', columns: [
        'inviter',
      ] },
    ],
    constraints: [
      { name: 'invite_code_code_key', constraint: 'unique', columns: ['code'] },
      { name: 'invite_code_inviter_key', constraint: 'unique', columns: ['inviter'] },
    ],
  }, InviteCodeRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_pos', name: 'player_x_z_idx_btree', algorithm: 'btree', columns: [
        'x',
        'z',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerCosmetic: __table({
    name: 'player_cosmetic',
    indexes: [
      { accessor: 'identity', name: 'player_cosmetic_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_cosmetic_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerCosmeticRow),
  playerSkill: __table({
    name: 'player_skill',
    indexes: [
      { accessor: 'identity', name: 'player_skill_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_skill_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerSkillRow),
  socialEvent: __table({
    name: 'social_event',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, SocialEventRow),
  trade: __table({
    name: 'trade',
    indexes: [
      { accessor: 'a', name: 'trade_a_idx_btree', algorithm: 'btree', columns: [
        'a',
      ] },
      { accessor: 'b', name: 'trade_b_idx_btree', algorithm: 'btree', columns: [
        'b',
      ] },
      { accessor: 'id', name: 'trade_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'trade_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TradeRow),
  trainingDummy: __table({
    name: 'training_dummy',
    indexes: [
      { accessor: 'id', name: 'training_dummy_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'training_dummy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TrainingDummyRow),
  tree: __table({
    name: 'tree',
    indexes: [
      { accessor: 'id', name: 'tree_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tree_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TreeRow),
  world: __table({
    name: 'world',
    indexes: [
      { accessor: 'id', name: 'world_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_friend", AddFriendReducer),
  __reducerSchema("attack", AttackReducer),
  __reducerSchema("attack_dummy", AttackDummyReducer),
  __reducerSchema("attack_giant", AttackGiantReducer),
  __reducerSchema("cancel", CancelReducer),
  __reducerSchema("cancel_trade_request", CancelTradeRequestReducer),
  __reducerSchema("configure_access", ConfigureAccessReducer),
  __reducerSchema("confirm_trade", ConfirmTradeReducer),
  __reducerSchema("craft", CraftReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("drop_item", DropItemReducer),
  __reducerSchema("eat_berry", EatBerryReducer),
  __reducerSchema("emote", EmoteReducer),
  __reducerSchema("follow", FollowReducer),
  __reducerSchema("garden_dev_ripen", GardenDevRipenReducer),
  __reducerSchema("grant_agent", GrantAgentReducer),
  __reducerSchema("grant_player", GrantPlayerReducer),
  __reducerSchema("harvest_garden", HarvestGardenReducer),
  __reducerSchema("move_item", MoveItemReducer),
  __reducerSchema("pickup_item", PickupItemReducer),
  __reducerSchema("plant_garden", PlantGardenReducer),
  __reducerSchema("redeem_invite", RedeemInviteReducer),
  __reducerSchema("remove_friend", RemoveFriendReducer),
  __reducerSchema("renew_grant", RenewGrantReducer),
  __reducerSchema("request_trade", RequestTradeReducer),
  __reducerSchema("respond_trade", RespondTradeReducer),
  __reducerSchema("revoke_player", RevokePlayerReducer),
  __reducerSchema("send_chat", SendChatReducer),
  __reducerSchema("set_appearance", SetAppearanceReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("set_target", SetTargetReducer),
  __reducerSchema("set_trade_offer", SetTradeOfferReducer),
  __reducerSchema("start_harvest", StartHarvestReducer),
  __reducerSchema("unwield", UnwieldReducer),
  __reducerSchema("wear_cosmetic", WearCosmeticReducer),
  __reducerSchema("wield_item", WieldItemReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

