// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  online: __t.bool(),
  connections: __t.u8(),
  lastSeenAt: __t.timestamp().name("last_seen_at"),
  x: __t.i32(),
  z: __t.i32(),
  facing: __t.u8(),
  targetX: __t.option(__t.i32()).name("target_x"),
  targetZ: __t.option(__t.i32()).name("target_z"),
  hp: __t.u8(),
  maxHp: __t.u8().name("max_hp"),
  state: __t.u8(),
  respawnTick: __t.u32().name("respawn_tick"),
  stance: __t.u8(),
  fightState: __t.u8().name("fight_state"),
  combatTarget: __t.option(__t.identity()).name("combat_target"),
  hostile: __t.bool(),
  nextSwingTick: __t.u32().name("next_swing_tick"),
  lastExchangeTick: __t.u32().name("last_exchange_tick"),
  outOfRangeTicks: __t.u8().name("out_of_range_ticks"),
  pending: __t.u8(),
  pendingId: __t.u64().name("pending_id"),
  harvestTreeId: __t.u32().name("harvest_tree_id"),
  harvestEndTick: __t.u32().name("harvest_end_tick"),
  eatCooldownUntilTick: __t.u32().name("eat_cooldown_until_tick"),
  lastInputTick: __t.u32().name("last_input_tick"),
  inputsThisTick: __t.u8().name("inputs_this_tick"),
});
