// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  name: __t.string(),
  hairStyle: __t.u8(),
  skinTone: __t.u8(),
  hairColor: __t.u8(),
  robeColor: __t.u8(),
  wrapColor: __t.u8(),
  bodyType: __t.u8(),
  faceShape: __t.u8(),
  eyeColor: __t.u8(),
  facialHair: __t.u8(),
  outfitStyle: __t.u8(),
  trouserColor: __t.u8(),
  bootColor: __t.u8(),
  accessory: __t.u8(),
  accessoryColor: __t.u8(),
};
