// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  runId: __t.u64().name("run_id"),
  slot: __t.u8(),
  state: __t.u8(),
  joinedTick: __t.u32().name("joined_tick"),
  awaySinceTick: __t.u32().name("away_since_tick"),
  awayCount: __t.u8().name("away_count"),
  downUntilTick: __t.u32().name("down_until_tick"),
  reviveSinceTick: __t.u32().name("revive_since_tick"),
  meals: __t.u8(),
});
