// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.u64().primaryKey().name("run_id"),
  hp: __t.u32(),
  maxHp: __t.u32().name("max_hp"),
  phase: __t.u8(),
  seed: __t.u32(),
  patternCount: __t.u32().name("pattern_count"),
  curKind: __t.u8().name("cur_kind"),
  curStart: __t.u32().name("cur_start"),
  curSeed: __t.u8().name("cur_seed"),
  curAimX: __t.i32().name("cur_aim_x"),
  curAimZ: __t.i32().name("cur_aim_z"),
  prevKind: __t.u8().name("prev_kind"),
  prevStart: __t.u32().name("prev_start"),
  prevSeed: __t.u8().name("prev_seed"),
  prevAimX: __t.i32().name("prev_aim_x"),
  prevAimZ: __t.i32().name("prev_aim_z"),
  starWave: __t.u32().name("star_wave"),
  starMask: __t.u8().name("star_mask"),
  hitTick0: __t.u32().name("hit_tick_0"),
  hitTick1: __t.u32().name("hit_tick_1"),
  hitTick2: __t.u32().name("hit_tick_2"),
  hitTick3: __t.u32().name("hit_tick_3"),
  hits0: __t.u8().name("hits_0"),
  hits1: __t.u8().name("hits_1"),
  hits2: __t.u8().name("hits_2"),
  hits3: __t.u8().name("hits_3"),
  stars0: __t.u8().name("stars_0"),
  stars1: __t.u8().name("stars_1"),
  stars2: __t.u8().name("stars_2"),
  stars3: __t.u8().name("stars_3"),
  dmg0: __t.u32().name("dmg_0"),
  dmg1: __t.u32().name("dmg_1"),
  dmg2: __t.u32().name("dmg_2"),
  dmg3: __t.u32().name("dmg_3"),
  downs0: __t.u8().name("downs_0"),
  downs1: __t.u8().name("downs_1"),
  downs2: __t.u8().name("downs_2"),
  downs3: __t.u8().name("downs_3"),
});
