// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  leader: __t.identity(),
  stage: __t.u8(),
  outcome: __t.u8(),
  mode: __t.u8(),
  isPublic: __t.bool().name("is_public"),
  rules: __t.u32(),
  partySize: __t.u8().name("party_size"),
  createdTick: __t.u32().name("created_tick"),
  queuedTick: __t.u32().name("queued_tick"),
  startTick: __t.u32().name("start_tick"),
  endTick: __t.u32().name("end_tick"),
  phase: __t.u8(),
  clearTicks: __t.u32().name("clear_ticks"),
});
