// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  a: __t.identity(),
  b: __t.identity(),
  accepted: __t.bool(),
  aOffer: __t.string().name("a_offer"),
  bOffer: __t.string().name("b_offer"),
  aConfirmed: __t.bool().name("a_confirmed"),
  bConfirmed: __t.bool().name("b_confirmed"),
  createdTick: __t.u32().name("created_tick"),
  aCoins: __t.u32().name("a_coins"),
  bCoins: __t.u32().name("b_coins"),
});
