// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccessPolicy = __t.object("AccessPolicy", {
  id: __t.u8(),
  owner: __t.identity(),
  gateway: __t.option(__t.identity()),
  requireAdmission: __t.bool(),
});
export type AccessPolicy = __Infer<typeof AccessPolicy>;

export const AdventureProfile = __t.object("AdventureProfile", {
  identity: __t.identity(),
  growingXp: __t.u32(),
  buildingXp: __t.u32(),
  exploringXp: __t.u32(),
  fightingXp: __t.u32(),
  befriendingXp: __t.u32(),
  feats: __t.u32(),
  loadout: __t.u32(),
  completions: __t.u32(),
  giantTrust: __t.u32(),
  stickClaimed: __t.bool(),
});
export type AdventureProfile = __Infer<typeof AdventureProfile>;

export const Appearance = __t.object("Appearance", {
  identity: __t.identity(),
  hairStyle: __t.u8(),
  skinTone: __t.u8(),
  hairColor: __t.u8(),
  robeColor: __t.u8(),
  wrapColor: __t.u8(),
  bodyType: __t.u8(),
  faceShape: __t.u8(),
  eyeColor: __t.u8(),
  facialHair: __t.u8(),
  outfitStyle: __t.u8(),
  trouserColor: __t.u8(),
  bootColor: __t.u8(),
  accessory: __t.u8(),
  accessoryColor: __t.u8(),
  setupComplete: __t.bool(),
});
export type Appearance = __Infer<typeof Appearance>;

export const BossConfig = __t.object("BossConfig", {
  id: __t.u8(),
  clatterhornOpen: __t.bool(),
  spireOpen: __t.bool(),
  spirePracticeOpen: __t.bool(),
  spireMaxRuns: __t.u8(),
  spireHpBase: __t.u32(),
  spireHpPerMember: __t.u32(),
  clatterHpBase: __t.u32(),
  clatterHpPerChallenger: __t.u32(),
});
export type BossConfig = __Infer<typeof BossConfig>;

export const BossEvent = __t.object("BossEvent", {
  tick: __t.u32(),
  boss: __t.u8(),
  kind: __t.u8(),
  runId: __t.u64(),
  player: __t.identity(),
  x: __t.i32(),
  z: __t.i32(),
  quantity: __t.u32(),
  value: __t.u32(),
  text: __t.string(),
});
export type BossEvent = __Infer<typeof BossEvent>;

export const BossNotice = __t.object("BossNotice", {
  tick: __t.u32(),
  boss: __t.u8(),
  kind: __t.u8(),
  player: __t.identity(),
  runId: __t.u64(),
  amount: __t.u32(),
  total: __t.u32(),
  hp: __t.u8(),
  half: __t.u8(),
  quantity: __t.u8(),
  itemId: __t.string(),
  x: __t.i32(),
  z: __t.i32(),
});
export type BossNotice = __Infer<typeof BossNotice>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  tick: __t.u32(),
  sentAt: __t.timestamp(),
  x: __t.i32(),
  z: __t.i32(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Clatterhorn = __t.object("Clatterhorn", {
  id: __t.u32(),
  x: __t.i32(),
  z: __t.i32(),
  hp: __t.u32(),
  maxHp: __t.u32(),
  state: __t.u8(),
  phase: __t.u8(),
  stateUntilTick: __t.u32(),
  attack: __t.u8(),
  dir: __t.u8(),
  endX: __t.i32(),
  endZ: __t.i32(),
  endKind: __t.u8(),
  chain: __t.u8(),
  attackCount: __t.u32(),
  bait: __t.u32(),
  swarmTick: __t.u32(),
  swarmSide: __t.u8(),
  swarmFree: __t.u8(),
  engagedTick: __t.u32(),
  lastHitTick: __t.u32(),
  challengers: __t.u32(),
  fightCount: __t.u32(),
  defeats: __t.u32(),
  owedLeft: __t.u32(),
});
export type Clatterhorn = __Infer<typeof Clatterhorn>;

export const ClatterhornCredit = __t.object("ClatterhornCredit", {
  identity: __t.identity(),
  fight: __t.u32(),
  damage: __t.u32(),
  lastHitTick: __t.u32(),
  owed: __t.u8(),
});
export type ClatterhornCredit = __Infer<typeof ClatterhornCredit>;

export const CombatEvent = __t.object("CombatEvent", {
  tick: __t.u32(),
  kind: __t.u8(),
  attacker: __t.identity(),
  defender: __t.identity(),
  damage: __t.u8(),
  itemId: __t.string(),
  defenderHp: __t.u8(),
});
export type CombatEvent = __Infer<typeof CombatEvent>;

export const DailyActivity = __t.object("DailyActivity", {
  key: __t.string(),
  day: __t.u32(),
  identity: __t.identity(),
  agent: __t.bool(),
  sessions: __t.u32(),
  playSeconds: __t.u32(),
  harvests: __t.u32(),
  gathered: __t.u32(),
  crafts: __t.u32(),
  kills: __t.u32(),
  deaths: __t.u32(),
  trades: __t.u32(),
  deposits: __t.u32(),
  chats: __t.u32(),
  actions: __t.string(),
});
export type DailyActivity = __Infer<typeof DailyActivity>;

export const DummyEvent = __t.object("DummyEvent", {
  tick: __t.u32(),
  dummyId: __t.u32(),
  attacker: __t.identity(),
  damage: __t.u8(),
  itemId: __t.string(),
  hp: __t.u8(),
  reset: __t.bool(),
});
export type DummyEvent = __Infer<typeof DummyEvent>;

export const EmoteCooldown = __t.object("EmoteCooldown", {
  identity: __t.identity(),
  lastTick: __t.u32(),
});
export type EmoteCooldown = __Infer<typeof EmoteCooldown>;

export const EmoteEvent = __t.object("EmoteEvent", {
  tick: __t.u32(),
  player: __t.identity(),
  emote: __t.u8(),
});
export type EmoteEvent = __Infer<typeof EmoteEvent>;

export const Expedition = __t.object("Expedition", {
  id: __t.u64(),
  leader: __t.identity(),
  stage: __t.string(),
  startedTick: __t.u32(),
  untilTick: __t.u32(),
  ripeTick: __t.u32(),
  x: __t.i32(),
  z: __t.i32(),
  carrier: __t.option(__t.identity()),
  mossCarrying: __t.bool(),
  mossPaid: __t.bool(),
  porter: __t.option(__t.identity()),
  lastActiveTick: __t.u32(),
  value: __t.u8(),
  split: __t.bool(),
  mossX: __t.i32(),
  mossZ: __t.i32(),
  pipX: __t.i32(),
  pipZ: __t.i32(),
  giantX: __t.i32(),
  giantZ: __t.i32(),
  hiddenUntil: __t.u32(),
  pipUntil: __t.u32(),
  giantUntil: __t.u32(),
  baitX: __t.i32(),
  baitZ: __t.i32(),
  baitUntil: __t.u32(),
  guardUntil: __t.u32(),
  message: __t.string(),
  destination: __t.string(),
});
export type Expedition = __Infer<typeof Expedition>;

export const ExpeditionCredit = __t.object("ExpeditionCredit", {
  key: __t.string(),
  expeditionId: __t.u64(),
  identity: __t.identity(),
  contributions: __t.u32(),
  rewarded: __t.bool(),
  tracked: __t.bool(),
});
export type ExpeditionCredit = __Infer<typeof ExpeditionCredit>;

export const ExpeditionMember = __t.object("ExpeditionMember", {
  identity: __t.identity(),
  expeditionId: __t.u64(),
  contributions: __t.u32(),
  cooldown: __t.u32(),
  tracked: __t.bool(),
});
export type ExpeditionMember = __Infer<typeof ExpeditionMember>;

export const Friend = __t.object("Friend", {
  id: __t.u64(),
  owner: __t.identity(),
  friend: __t.identity(),
  since: __t.timestamp(),
});
export type Friend = __Infer<typeof Friend>;

export const FriendlyDuel = __t.object("FriendlyDuel", {
  id: __t.u64(),
  a: __t.identity(),
  b: __t.identity(),
  stage: __t.string(),
  startsTick: __t.u32(),
  expiresTick: __t.u32(),
  aHp: __t.u8(),
  bHp: __t.u8(),
  nextSwingTick: __t.u32(),
  turnA: __t.bool(),
  result: __t.string(),
});
export type FriendlyDuel = __Infer<typeof FriendlyDuel>;

export const FrontierObject = __t.object("FrontierObject", {
  key: __t.string(),
  kind: __t.string(),
  region: __t.string(),
  data: __t.string(),
});
export type FrontierObject = __Infer<typeof FrontierObject>;

export const FrontierPrivate = __t.object("FrontierPrivate", {
  key: __t.string(),
  kind: __t.string(),
  data: __t.string(),
});
export type FrontierPrivate = __Infer<typeof FrontierPrivate>;

export const FrontierView = __t.object("FrontierView", {
  key: __t.string(),
  owner: __t.identity(),
  kind: __t.string(),
  data: __t.string(),
  source: __t.string(),
});
export type FrontierView = __Infer<typeof FrontierView>;

export const GardenPlot = __t.object("GardenPlot", {
  id: __t.u64(),
  owner: __t.identity(),
  plot: __t.u8(),
  itemId: __t.string(),
  plantedAtMicros: __t.u64(),
});
export type GardenPlot = __Infer<typeof GardenPlot>;

export const GardenShowcase = __t.object("GardenShowcase", {
  identity: __t.identity(),
  plants: __t.string(),
});
export type GardenShowcase = __Infer<typeof GardenShowcase>;

export const Giant = __t.object("Giant", {
  id: __t.u32(),
  x: __t.i32(),
  z: __t.i32(),
  hp: __t.u32(),
  maxHp: __t.u32(),
  state: __t.u8(),
  attack: __t.u8(),
  stateUntilTick: __t.u32(),
  slamX: __t.i32(),
  slamZ: __t.i32(),
  attackCount: __t.u32(),
  respawnTick: __t.u32(),
  lastHitTick: __t.u32(),
});
export type Giant = __Infer<typeof Giant>;

export const GiantContribution = __t.object("GiantContribution", {
  identity: __t.identity(),
  giantId: __t.u32(),
  damage: __t.u32(),
  lastHitTick: __t.u32(),
});
export type GiantContribution = __Infer<typeof GiantContribution>;

export const GiantEvent = __t.object("GiantEvent", {
  tick: __t.u32(),
  giantId: __t.u32(),
  kind: __t.u8(),
  player: __t.identity(),
  damage: __t.u8(),
  itemId: __t.string(),
  quantity: __t.u8(),
  hp: __t.u32(),
  x: __t.i32(),
  z: __t.i32(),
});
export type GiantEvent = __Infer<typeof GiantEvent>;

export const GiantRaid = __t.object("GiantRaid", {
  id: __t.u32(),
  awake: __t.bool(),
  nextWakeAtMicros: __t.u64(),
  raidEndsAtMicros: __t.u64(),
  announced: __t.u8(),
  raidPlayers: __t.u32(),
  lastOutcome: __t.u8(),
  raidCount: __t.u32(),
});
export type GiantRaid = __Infer<typeof GiantRaid>;

export const GroundItem = __t.object("GroundItem", {
  id: __t.u64(),
  itemId: __t.string(),
  quantity: __t.u8(),
  x: __t.i32(),
  z: __t.i32(),
  droppedBy: __t.identity(),
  droppedTick: __t.u32(),
  expiresTick: __t.u32(),
  droppedOnDeath: __t.bool(),
});
export type GroundItem = __Infer<typeof GroundItem>;

export const IdleState = __t.object("IdleState", {
  identity: __t.identity(),
  activeTick: __t.u32(),
  loggedOut: __t.bool(),
});
export type IdleState = __Infer<typeof IdleState>;

export const InventorySlot = __t.object("InventorySlot", {
  id: __t.u64(),
  owner: __t.identity(),
  slot: __t.u8(),
  itemId: __t.string(),
  quantity: __t.u8(),
});
export type InventorySlot = __Infer<typeof InventorySlot>;

export const InviteCode = __t.object("InviteCode", {
  code: __t.string(),
  inviter: __t.identity(),
  expiresAtMicros: __t.u64(),
});
export type InviteCode = __Infer<typeof InviteCode>;

export const IslandProject = __t.object("IslandProject", {
  id: __t.u8(),
  wood: __t.u32(),
  obsidian: __t.u32(),
  meals: __t.u32(),
});
export type IslandProject = __Infer<typeof IslandProject>;

export const Mentee = __t.object("Mentee", {
  identity: __t.identity(),
  inviter: __t.option(__t.identity()),
  mentor: __t.option(__t.identity()),
  creditedAt: __t.option(__t.timestamp()),
  milestones: __t.u8(),
});
export type Mentee = __Infer<typeof Mentee>;

export const MentorStat = __t.object("MentorStat", {
  identity: __t.identity(),
  mentees: __t.u32(),
});
export type MentorStat = __Infer<typeof MentorStat>;

export const PendingDeposit = __t.object("PendingDeposit", {
  identity: __t.identity(),
  boxId: __t.u32(),
  itemId: __t.string(),
  quantity: __t.u8(),
  doneTick: __t.u32(),
});
export type PendingDeposit = __Infer<typeof PendingDeposit>;

export const PlayStats = __t.object("PlayStats", {
  identity: __t.identity(),
  firstJoinAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
  sessionStartedAt: __t.option(__t.timestamp()),
  sessions: __t.u32(),
  totalPlayMicros: __t.u64(),
  firstBerryAt: __t.option(__t.timestamp()),
  firstStickAt: __t.option(__t.timestamp()),
  reachedHedgeAt: __t.option(__t.timestamp()),
  reachedCoastAt: __t.option(__t.timestamp()),
  firstCraftAt: __t.option(__t.timestamp()),
  deaths: __t.u32(),
  lastStep: __t.string(),
});
export type PlayStats = __Infer<typeof PlayStats>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  connections: __t.u8(),
  lastSeenAt: __t.timestamp(),
  x: __t.i32(),
  z: __t.i32(),
  facing: __t.u8(),
  targetX: __t.option(__t.i32()),
  targetZ: __t.option(__t.i32()),
  hp: __t.u8(),
  maxHp: __t.u8(),
  state: __t.u8(),
  respawnTick: __t.u32(),
  stance: __t.u8(),
  fightState: __t.u8(),
  combatTarget: __t.option(__t.identity()),
  hostile: __t.bool(),
  nextSwingTick: __t.u32(),
  lastExchangeTick: __t.u32(),
  outOfRangeTicks: __t.u8(),
  pending: __t.u8(),
  pendingId: __t.u64(),
  harvestTreeId: __t.u32(),
  harvestEndTick: __t.u32(),
  eatCooldownUntilTick: __t.u32(),
  lastInputTick: __t.u32(),
  inputsThisTick: __t.u8(),
  weapon: __t.string(),
  region: __t.string(),
  load: __t.u8(),
});
export type Player = __Infer<typeof Player>;

export const PlayerCosmetic = __t.object("PlayerCosmetic", {
  identity: __t.identity(),
  unlocked: __t.u32(),
  head: __t.u8(),
  neck: __t.u8(),
});
export type PlayerCosmetic = __Infer<typeof PlayerCosmetic>;

export const PlayerGrant = __t.object("PlayerGrant", {
  identity: __t.identity(),
  issuer: __t.identity(),
  agent: __t.bool(),
  expiresAtMicros: __t.u64(),
  combat: __t.bool(),
  chat: __t.bool(),
});
export type PlayerGrant = __Infer<typeof PlayerGrant>;

export const PlayerSkill = __t.object("PlayerSkill", {
  identity: __t.identity(),
  foragingXp: __t.u32(),
  beachcombingXp: __t.u32(),
  craftingXp: __t.u32(),
});
export type PlayerSkill = __Infer<typeof PlayerSkill>;

export const SocialEvent = __t.object("SocialEvent", {
  tick: __t.u32(),
  kind: __t.u8(),
  from: __t.identity(),
  to: __t.identity(),
  text: __t.string(),
});
export type SocialEvent = __Infer<typeof SocialEvent>;

export const SocialPair = __t.object("SocialPair", {
  pair: __t.string(),
  lastNoticeMicros: __t.u64(),
  friendNoticed: __t.bool(),
  redeemedCode: __t.string(),
});
export type SocialPair = __Infer<typeof SocialPair>;

export const SpireFight = __t.object("SpireFight", {
  runId: __t.u64(),
  hp: __t.u32(),
  maxHp: __t.u32(),
  phase: __t.u8(),
  seed: __t.u32(),
  patternCount: __t.u32(),
  curKind: __t.u8(),
  curStart: __t.u32(),
  curSeed: __t.u8(),
  curAimX: __t.i32(),
  curAimZ: __t.i32(),
  prevKind: __t.u8(),
  prevStart: __t.u32(),
  prevSeed: __t.u8(),
  prevAimX: __t.i32(),
  prevAimZ: __t.i32(),
  starWave: __t.u32(),
  starMask: __t.u8(),
  hitTick0: __t.u32(),
  hitTick1: __t.u32(),
  hitTick2: __t.u32(),
  hitTick3: __t.u32(),
  hits0: __t.u8(),
  hits1: __t.u8(),
  hits2: __t.u8(),
  hits3: __t.u8(),
  stars0: __t.u8(),
  stars1: __t.u8(),
  stars2: __t.u8(),
  stars3: __t.u8(),
  dmg0: __t.u32(),
  dmg1: __t.u32(),
  dmg2: __t.u32(),
  dmg3: __t.u32(),
  downs0: __t.u8(),
  downs1: __t.u8(),
  downs2: __t.u8(),
  downs3: __t.u8(),
});
export type SpireFight = __Infer<typeof SpireFight>;

export const SpireMember = __t.object("SpireMember", {
  identity: __t.identity(),
  runId: __t.u64(),
  slot: __t.u8(),
  state: __t.u8(),
  joinedTick: __t.u32(),
  awaySinceTick: __t.u32(),
  awayCount: __t.u8(),
  downUntilTick: __t.u32(),
  reviveSinceTick: __t.u32(),
  meals: __t.u8(),
});
export type SpireMember = __Infer<typeof SpireMember>;

export const SpireRun = __t.object("SpireRun", {
  id: __t.u64(),
  leader: __t.identity(),
  stage: __t.u8(),
  outcome: __t.u8(),
  mode: __t.u8(),
  isPublic: __t.bool(),
  rules: __t.u32(),
  partySize: __t.u8(),
  createdTick: __t.u32(),
  queuedTick: __t.u32(),
  startTick: __t.u32(),
  endTick: __t.u32(),
  phase: __t.u8(),
  clearTicks: __t.u32(),
});
export type SpireRun = __Infer<typeof SpireRun>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const Trade = __t.object("Trade", {
  id: __t.u64(),
  a: __t.identity(),
  b: __t.identity(),
  accepted: __t.bool(),
  aOffer: __t.string(),
  bOffer: __t.string(),
  aConfirmed: __t.bool(),
  bConfirmed: __t.bool(),
  createdTick: __t.u32(),
  aCoins: __t.u32(),
  bCoins: __t.u32(),
  swapTick: __t.u32(),
  aHp: __t.u8(),
  bHp: __t.u8(),
});
export type Trade = __Infer<typeof Trade>;

export const TrainingDummy = __t.object("TrainingDummy", {
  id: __t.u32(),
  x: __t.i32(),
  z: __t.i32(),
  hp: __t.u8(),
  maxHp: __t.u8(),
  lastHitTick: __t.u32(),
});
export type TrainingDummy = __Infer<typeof TrainingDummy>;

export const Tree = __t.object("Tree", {
  id: __t.u32(),
  x: __t.i32(),
  z: __t.i32(),
  itemId: __t.string(),
  cooldownUntilTick: __t.u32(),
  harvester: __t.option(__t.identity()),
  kind: __t.u8(),
});
export type Tree = __Infer<typeof Tree>;

export const World = __t.object("World", {
  id: __t.u8(),
  tick: __t.u32(),
  tickStartedAt: __t.timestamp(),
});
export type World = __Infer<typeof World>;

