// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Appearance = __t.object("Appearance", {
  identity: __t.identity(),
  hairStyle: __t.u8(),
  skinTone: __t.u8(),
  hairColor: __t.u8(),
  robeColor: __t.u8(),
  wrapColor: __t.u8(),
});
export type Appearance = __Infer<typeof Appearance>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  tick: __t.u32(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const CombatEvent = __t.object("CombatEvent", {
  tick: __t.u32(),
  kind: __t.u8(),
  attacker: __t.identity(),
  defender: __t.identity(),
  damage: __t.u8(),
  attackerStance: __t.u8(),
  defenderStance: __t.u8(),
  attackerState: __t.u8(),
  defenderState: __t.u8(),
  defenderHp: __t.u8(),
});
export type CombatEvent = __Infer<typeof CombatEvent>;

export const GroundItem = __t.object("GroundItem", {
  id: __t.u64(),
  itemId: __t.string(),
  quantity: __t.u8(),
  x: __t.i32(),
  z: __t.i32(),
  droppedBy: __t.identity(),
  droppedTick: __t.u32(),
  expiresTick: __t.u32(),
  droppedOnDeath: __t.bool(),
});
export type GroundItem = __Infer<typeof GroundItem>;

export const InventorySlot = __t.object("InventorySlot", {
  id: __t.u64(),
  owner: __t.identity(),
  slot: __t.u8(),
  itemId: __t.string(),
  quantity: __t.u8(),
});
export type InventorySlot = __Infer<typeof InventorySlot>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  connections: __t.u8(),
  lastSeenAt: __t.timestamp(),
  x: __t.i32(),
  z: __t.i32(),
  facing: __t.u8(),
  targetX: __t.option(__t.i32()),
  targetZ: __t.option(__t.i32()),
  hp: __t.u8(),
  maxHp: __t.u8(),
  state: __t.u8(),
  respawnTick: __t.u32(),
  stance: __t.u8(),
  fightState: __t.u8(),
  combatTarget: __t.option(__t.identity()),
  hostile: __t.bool(),
  nextSwingTick: __t.u32(),
  lastExchangeTick: __t.u32(),
  outOfRangeTicks: __t.u8(),
  pending: __t.u8(),
  pendingId: __t.u64(),
  harvestTreeId: __t.u32(),
  harvestEndTick: __t.u32(),
  eatCooldownUntilTick: __t.u32(),
  lastInputTick: __t.u32(),
  inputsThisTick: __t.u8(),
});
export type Player = __Infer<typeof Player>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const Tree = __t.object("Tree", {
  id: __t.u32(),
  x: __t.i32(),
  z: __t.i32(),
  itemId: __t.string(),
  cooldownUntilTick: __t.u32(),
  harvester: __t.option(__t.identity()),
});
export type Tree = __Infer<typeof Tree>;

export const World = __t.object("World", {
  id: __t.u8(),
  tick: __t.u32(),
  tickStartedAt: __t.timestamp(),
});
export type World = __Infer<typeof World>;

