/** Exercises the real wardrobe UI; requires a running local review game. */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const pw=require(process.env.PLAYWRIGHT_MODULE??'playwright');
const engine=process.env.ENGINE??'chromium';
const out=process.env.SHOT_DIR??'../docs/art/game-review/wardrobe';
fs.mkdirSync(out,{recursive:true});
const browser=await pw[engine].launch(engine==='chromium'?{channel:'chrome'}:{});
const report={engine,version:browser.version(),checks:[],errors:[]};
const check=(label,pass,detail)=>{report.checks.push({label,pass:Boolean(pass),detail});if(!pass)throw new Error(label);console.log('PASS',label)};
const ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,deviceScaleFactor:2,...(engine!=='firefox'?{isMobile:true}:{})});
const observerContext=await browser.newContext({viewport:{width:1440,height:900}});
const observer=await observerContext.newPage();
const page=await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));
try{
 await page.goto(process.env.GAME_URL??'http://127.0.0.1:5173');
 await page.waitForFunction(()=>window.__berigame?.me&&!document.querySelector('.loading-screen'),null,{timeout:30000});
 const initial=await page.evaluate(()=>window.__berigame.me);
 const step=await page.evaluate(([x,z])=>window.__berigameProject(x,z,0),[initial.x,initial.z+3]);
 await page.touchscreen.tap(step.x,step.y);
 await page.waitForFunction(z=>window.__berigame.me.z===z,initial.z+3,{timeout:10000});
 const identity=initial.hex;
 await observer.goto(process.env.GAME_URL??'http://127.0.0.1:5173');
 await observer.waitForFunction(hex=>window.__berigameAvatars?.().some(a=>a.identity===hex),identity,{timeout:30000});
 await page.getByRole('button',{name:'Style',exact:true}).tap();
 await page.getByRole('button',{name:'Cropped',exact:true}).tap();
 await page.getByRole('button',{name:'Robe: Forest',exact:true}).tap();
 await page.waitForTimeout(1200);
 await page.waitForFunction(hex=>window.__berigameAvatars?.().some(a=>a.identity===hex&&a.appearance.hairStyle===1&&a.appearance.robeColor===1),identity);
 const remoteDraft=await observer.evaluate(hex=>window.__berigameAvatars().find(a=>a.identity===hex),identity);
 check('unsaved preview affects only the local actor',remoteDraft.appearance.hairStyle===0&&remoteDraft.appearance.robeColor===0,remoteDraft);
 await page.screenshot({path:path.join(out,`${engine}-preview-portrait.png`)});
 await page.getByRole('button',{name:'Cancel',exact:true}).tap();
 await page.getByRole('button',{name:'Style',exact:true}).tap();
 check('Cancel restores the saved hair and robe choices',await page.getByRole('button',{name:'Tousled',exact:true}).getAttribute('aria-pressed')==='true'&&await page.getByRole('button',{name:'Robe: Blue',exact:true}).getAttribute('aria-pressed')==='true');
 const names=['Topknot','Skin tone: Brown','Hair color: Silver','Robe: Plum','Wraps: Slate'];
 for(const name of names)await page.getByRole('button',{name,exact:true}).tap();
 await page.waitForTimeout(1200);
 const framing=await page.evaluate(()=>{const me=window.__berigame.me;const panel=document.querySelector('.appearance-panel').getBoundingClientRect();return{feet:window.__berigameProject(me.x,me.z,0),head:window.__berigameProject(me.x,me.z,2.1),panelTop:panel.top,hudTop:document.querySelector('.stance-hud').getBoundingClientRect().top,buttons:[...document.querySelectorAll('.appearance-actions button')].map(e=>({label:e.textContent,...e.getBoundingClientRect().toJSON()}))}});
 check('portrait actor is above the wardrobe sheet',framing.feet.y<framing.panelTop&&framing.head.y>60,framing);
 check('portrait Save and Cancel stay above the combat HUD',framing.buttons.every(b=>b.height>=44&&b.y+b.height<=framing.hudTop),framing);
 await page.screenshot({path:path.join(out,`${engine}-edited-portrait.png`)});
 await page.getByRole('button',{name:'Save style',exact:true}).tap();
 await page.locator('.appearance-panel').waitFor({state:'hidden'});
 await observer.waitForFunction(hex=>window.__berigameAvatars?.().some(a=>a.identity===hex&&a.appearance.hairStyle===2&&a.appearance.skinTone===4&&a.appearance.hairColor===3&&a.appearance.robeColor===3&&a.appearance.wrapColor===2),identity,{timeout:15000});
 check('saved full appearance reaches another client renderer',true,await observer.evaluate(hex=>window.__berigameAvatars().find(a=>a.identity===hex),identity));
 await observer.screenshot({path:path.join(out,`${engine}-remote-saved.png`)});
 await page.reload();
 await page.waitForFunction(()=>window.__berigame?.me&&!document.querySelector('.loading-screen'),null,{timeout:30000});
 await page.getByRole('button',{name:'Style',exact:true}).tap();
 for(const name of names)check(`saved ${name} persists after reload`,await page.getByRole('button',{name,exact:true}).getAttribute('aria-pressed')==='true');
 await page.setViewportSize({width:360,height:740});await page.waitForTimeout(1200);
 const compact=await page.evaluate(()=>{const a=document.querySelector('.world-header').getBoundingClientRect(),b=document.querySelector('.game-toolbar').getBoundingClientRect(),m=window.__berigame.me;return{headerRight:a.right,toolbarLeft:b.left,feet:window.__berigameProject(m.x,m.z,0),panelTop:document.querySelector('.appearance-panel').getBoundingClientRect().top}});
 check('360px toolbar clears brand and full actor clears sheet',compact.headerRight<=compact.toolbarLeft&&compact.feet.y<compact.panelTop,compact);
 await page.screenshot({path:path.join(out,`${engine}-compact.png`)});
 await page.setViewportSize({width:844,height:390});await page.waitForTimeout(1200);await page.screenshot({path:path.join(out,`${engine}-landscape.png`)});
 const save=await page.getByRole('button',{name:'Save style',exact:true}).boundingBox();check('landscape wardrobe actions fit',save&&save.y+save.height<=390);
 await page.getByRole('button',{name:'Close character style',exact:true}).tap();
 await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(1200);await page.getByRole('button',{name:'Style',exact:true}).tap();await page.screenshot({path:path.join(out,`${engine}-desktop.png`)});
 check('no page errors',report.errors.length===0);
 report.status='passed';
}catch(e){report.status='failed';report.failure=String(e.stack??e);await page.screenshot({path:path.join(out,`${engine}-failure.png`)}).catch(()=>{});console.error(e);process.exitCode=1;}
finally{fs.writeFileSync(path.join(out,`${engine}-appearance.json`),JSON.stringify(report,null,2));await browser.close();}
