import type { InferSchema, ReducerCtx } from 'spacetimedb/server';
import type spacetimedb from '../schema';

export type Ctx = ReducerCtx<InferSchema<typeof spacetimedb>>;
export type PlayerRow = NonNullable<ReturnType<Ctx['db']['player']['identity']['find']>>;
export type TreeRow = NonNullable<ReturnType<Ctx['db']['tree']['id']['find']>>;
export type GroundItemRow = NonNullable<ReturnType<Ctx['db']['groundItem']['id']['find']>>;
export type InventorySlotRow = NonNullable<ReturnType<Ctx['db']['inventorySlot']['id']['find']>>;
export type WorldRow = NonNullable<ReturnType<Ctx['db']['world']['id']['find']>>;
export type TrainingDummyRow = NonNullable<ReturnType<Ctx['db']['trainingDummy']['id']['find']>>;
export type TradeRow = NonNullable<ReturnType<Ctx['db']['trade']['id']['find']>>;
export type GiantRow = NonNullable<ReturnType<Ctx['db']['giant']['id']['find']>>;
export type PlayerSkillRow = NonNullable<ReturnType<Ctx['db']['playerSkill']['identity']['find']>>;
export type PlayerCosmeticRow = NonNullable<ReturnType<Ctx['db']['playerCosmetic']['identity']['find']>>;
export type GiantRaidRow = NonNullable<ReturnType<Ctx['db']['giantRaid']['id']['find']>>;
export type MenteeRow = NonNullable<ReturnType<Ctx['db']['mentee']['identity']['find']>>;
export type GardenPlotRow = NonNullable<ReturnType<Ctx['db']['gardenPlot']['id']['find']>>;
export type BossConfigRow = NonNullable<ReturnType<Ctx['db']['bossConfig']['id']['find']>>;
export type ClatterhornRow = NonNullable<ReturnType<Ctx['db']['clatterhorn']['id']['find']>>;
export type ClatterhornCreditRow = NonNullable<ReturnType<Ctx['db']['clatterhornCredit']['identity']['find']>>;
export type SpireRunRow = NonNullable<ReturnType<Ctx['db']['spireRun']['id']['find']>>;
export type SpireMemberRow = NonNullable<ReturnType<Ctx['db']['spireMember']['identity']['find']>>;
export type SpireFightRow = NonNullable<ReturnType<Ctx['db']['spireFight']['runId']['find']>>;
