// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddFriendReducer from "../add_friend_reducer";
import AttackReducer from "../attack_reducer";
import AttackDummyReducer from "../attack_dummy_reducer";
import AttackGiantReducer from "../attack_giant_reducer";
import CancelReducer from "../cancel_reducer";
import CancelTradeRequestReducer from "../cancel_trade_request_reducer";
import ConfigureAccessReducer from "../configure_access_reducer";
import ConfirmTradeReducer from "../confirm_trade_reducer";
import CraftReducer from "../craft_reducer";
import CreateInviteReducer from "../create_invite_reducer";
import DropItemReducer from "../drop_item_reducer";
import EatBerryReducer from "../eat_berry_reducer";
import EmoteReducer from "../emote_reducer";
import FollowReducer from "../follow_reducer";
import GardenDevRipenReducer from "../garden_dev_ripen_reducer";
import GrantAgentReducer from "../grant_agent_reducer";
import GrantPlayerReducer from "../grant_player_reducer";
import HarvestGardenReducer from "../harvest_garden_reducer";
import MoveItemReducer from "../move_item_reducer";
import PickupItemReducer from "../pickup_item_reducer";
import PlantGardenReducer from "../plant_garden_reducer";
import RedeemInviteReducer from "../redeem_invite_reducer";
import RemoveFriendReducer from "../remove_friend_reducer";
import RenewGrantReducer from "../renew_grant_reducer";
import RequestTradeReducer from "../request_trade_reducer";
import RespondTradeReducer from "../respond_trade_reducer";
import RevokePlayerReducer from "../revoke_player_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetAppearanceReducer from "../set_appearance_reducer";
import SetNameReducer from "../set_name_reducer";
import SetTargetReducer from "../set_target_reducer";
import SetTradeOfferReducer from "../set_trade_offer_reducer";
import StartHarvestReducer from "../start_harvest_reducer";
import TriggerGiantRaidReducer from "../trigger_giant_raid_reducer";
import UnwieldReducer from "../unwield_reducer";
import WearCosmeticReducer from "../wear_cosmetic_reducer";
import WieldItemReducer from "../wield_item_reducer";

export type AddFriendParams = __Infer<typeof AddFriendReducer>;
export type AttackParams = __Infer<typeof AttackReducer>;
export type AttackDummyParams = __Infer<typeof AttackDummyReducer>;
export type AttackGiantParams = __Infer<typeof AttackGiantReducer>;
export type CancelParams = __Infer<typeof CancelReducer>;
export type CancelTradeRequestParams = __Infer<typeof CancelTradeRequestReducer>;
export type ConfigureAccessParams = __Infer<typeof ConfigureAccessReducer>;
export type ConfirmTradeParams = __Infer<typeof ConfirmTradeReducer>;
export type CraftParams = __Infer<typeof CraftReducer>;
export type CreateInviteParams = __Infer<typeof CreateInviteReducer>;
export type DropItemParams = __Infer<typeof DropItemReducer>;
export type EatBerryParams = __Infer<typeof EatBerryReducer>;
export type EmoteParams = __Infer<typeof EmoteReducer>;
export type FollowParams = __Infer<typeof FollowReducer>;
export type GardenDevRipenParams = __Infer<typeof GardenDevRipenReducer>;
export type GrantAgentParams = __Infer<typeof GrantAgentReducer>;
export type GrantPlayerParams = __Infer<typeof GrantPlayerReducer>;
export type HarvestGardenParams = __Infer<typeof HarvestGardenReducer>;
export type MoveItemParams = __Infer<typeof MoveItemReducer>;
export type PickupItemParams = __Infer<typeof PickupItemReducer>;
export type PlantGardenParams = __Infer<typeof PlantGardenReducer>;
export type RedeemInviteParams = __Infer<typeof RedeemInviteReducer>;
export type RemoveFriendParams = __Infer<typeof RemoveFriendReducer>;
export type RenewGrantParams = __Infer<typeof RenewGrantReducer>;
export type RequestTradeParams = __Infer<typeof RequestTradeReducer>;
export type RespondTradeParams = __Infer<typeof RespondTradeReducer>;
export type RevokePlayerParams = __Infer<typeof RevokePlayerReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetAppearanceParams = __Infer<typeof SetAppearanceReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetTargetParams = __Infer<typeof SetTargetReducer>;
export type SetTradeOfferParams = __Infer<typeof SetTradeOfferReducer>;
export type StartHarvestParams = __Infer<typeof StartHarvestReducer>;
export type TriggerGiantRaidParams = __Infer<typeof TriggerGiantRaidReducer>;
export type UnwieldParams = __Infer<typeof UnwieldReducer>;
export type WearCosmeticParams = __Infer<typeof WearCosmeticReducer>;
export type WieldItemParams = __Infer<typeof WieldItemReducer>;

