// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AttackReducer from "../attack_reducer";
import AttackDummyReducer from "../attack_dummy_reducer";
import AttackGiantReducer from "../attack_giant_reducer";
import CancelReducer from "../cancel_reducer";
import ConfigureAccessReducer from "../configure_access_reducer";
import CraftReducer from "../craft_reducer";
import DropItemReducer from "../drop_item_reducer";
import EatBerryReducer from "../eat_berry_reducer";
import EmoteReducer from "../emote_reducer";
import FollowReducer from "../follow_reducer";
import GrantAgentReducer from "../grant_agent_reducer";
import GrantPlayerReducer from "../grant_player_reducer";
import MoveItemReducer from "../move_item_reducer";
import PickupItemReducer from "../pickup_item_reducer";
import RenewGrantReducer from "../renew_grant_reducer";
import RevokePlayerReducer from "../revoke_player_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetAppearanceReducer from "../set_appearance_reducer";
import SetNameReducer from "../set_name_reducer";
import SetTargetReducer from "../set_target_reducer";
import StartHarvestReducer from "../start_harvest_reducer";
import UnwieldReducer from "../unwield_reducer";
import WieldItemReducer from "../wield_item_reducer";

export type AttackParams = __Infer<typeof AttackReducer>;
export type AttackDummyParams = __Infer<typeof AttackDummyReducer>;
export type AttackGiantParams = __Infer<typeof AttackGiantReducer>;
export type CancelParams = __Infer<typeof CancelReducer>;
export type ConfigureAccessParams = __Infer<typeof ConfigureAccessReducer>;
export type CraftParams = __Infer<typeof CraftReducer>;
export type DropItemParams = __Infer<typeof DropItemReducer>;
export type EatBerryParams = __Infer<typeof EatBerryReducer>;
export type EmoteParams = __Infer<typeof EmoteReducer>;
export type FollowParams = __Infer<typeof FollowReducer>;
export type GrantAgentParams = __Infer<typeof GrantAgentReducer>;
export type GrantPlayerParams = __Infer<typeof GrantPlayerReducer>;
export type MoveItemParams = __Infer<typeof MoveItemReducer>;
export type PickupItemParams = __Infer<typeof PickupItemReducer>;
export type RenewGrantParams = __Infer<typeof RenewGrantReducer>;
export type RevokePlayerParams = __Infer<typeof RevokePlayerReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetAppearanceParams = __Infer<typeof SetAppearanceReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetTargetParams = __Infer<typeof SetTargetReducer>;
export type StartHarvestParams = __Infer<typeof StartHarvestReducer>;
export type UnwieldParams = __Infer<typeof UnwieldReducer>;
export type WieldItemParams = __Infer<typeof WieldItemReducer>;

